#!/usr/bin/python3
import os
import sys
import json
import urllib
import urllib.request
import time
import re
import argparse
import base64
import requests

import shlex
import subprocess

if __name__ == '__main__':

  # submission template
  dctSubmission = {
    "app": "rep_movsd-nextflow_node",
    "staging": False,
    "checkedout": False,
    "application": {
      "command": "Server",
      "geometry": "1024x768"
    },
    "machine": {
      "type": "micro",
      "nodes": 1
    },
    "vault": {
      "name": "sandbox",
      "readonly": True,
      "force": False
    },
    "publicip": True,
  }

  sUser = os.environ.get('NF_JARVICE_USER')
  sAPIKey = os.environ.get('NF_JARVICE_APIKEY')
  sDalUUID = os.environ.get('NF_JARVICE_DAL_UUID')
  if (sUser is None) or (sAPIKey is None) or (sDalUUID is None):
    print('Environment variables NF_JARVICE_USER and NF_JARVICE_APIKEY and NF_JARVICE_DAL_UUID not set')
    sys.exit(-1)

  if len(sys.argv) > 1:
    sJobName = sys.argv[1]
  else:
    print('Launching nextflow helper app')
    print('-'*79)

    dctSubmission['user'] = {'username': sUser, 'apikey': sAPIKey}

    url = 'https://jarvice-development-api.jarvicedev.com/api/jarvice/submit'
    headers = {'Content-Type': 'application/json'}
    response = requests.post(url, headers=headers, json=dctSubmission)

    dctRet = response.json()
    print(dctRet)

    if 'error' in dctRet:
      sys.exit(-1)

    sJobNum = str(dctRet['number'])
    sJobName = dctRet['name']

    # Wait for job to start
    N = 3
    while True:
      url = f'https://jarvice-development-dal.jarvicedev.com/api/jobList?uuid={sDalUUID}&jobnum={sJobNum}&fields=job_status'
      response = requests.get(url)
      dctRet = response.json()

      if sJobNum in dctRet:
        sStatus = dctRet[sJobNum]['job_status']
        print(f'Job status for {sJobNum}: {sStatus} {N * "."}', end='\r')
        N += 1
        if sStatus == 'PROCESSING STARTING':
          break
      else:
        print(json.dumps(dctRet))
      time.sleep(5)

  print('-'*79)

  # Wait for job RT info
  N=3
  while True:
    print(f'Fetching IP address {N * "."}', end='\r')
    N += 1
    url = f'https://jarvice-development-dal.jarvicedev.com/api/runtimeInfo?uuid={sDalUUID}&jobname={sJobName}'
    response = requests.get(url)
    dctRet = response.json()

    if 'address' in dctRet:
      sAddr = dctRet['address']
      print()
      print(sAddr)
      break
    else:
      print(json.dumps(dctRet))
    time.sleep(5)

  print('-'*79)

  # Disable all the warnings about unknown hosts
  cmd = f'ssh -o "UserKnownHostsFile=/dev/null" -oStrictHostKeyChecking=no nimbix@{sAddr} -t "cd /data/; sudo chown nimbix:nimbix *; NF_JARVICE_USER={sUser} NF_JARVICE_APIKEY={sAPIKey} bash -l" '
  print(f'Starting SSH to job node nimbix@{sAddr}')
  print('-'*79)

  os.system(cmd)
  print('-'*79)

  print('Killing job')
  url = f'https://jarvice-development-dal.jarvicedev.com/api/runtimeShutdown?uuid={sDalUUID}&jobname={sJobName}'
  response = requests.get(url)
  dctRet = response.json()

  if not dctRet.get('status', False):
    print('Error terminating job')
    print(json.dumps(dctRet))
