#!/usr/bin/python3
import os
import sys
import json
import urllib
import urllib.request
import time
import re
import argparse
import base64
import requests


if __name__ == '__main__':

  # submission template
  dctSubmission = {
      'vault': {
      'name': 'sandbox',
      'readonly': False,
      'force': False
    }
  }

  parser = argparse.ArgumentParser()
  parser.add_argument('--opts', '-u', required=False, help='Cluster Options as JSON')
  parser.add_argument('--machine', '-m', required=False, default='n0', help='The machine type to run the script on')
  parser.add_argument('--nodes', '-n', required=False, type=int, default=1, help='Number of CPU nodes to use for the script')
  parser.add_argument('--container', '-c', required=False, help='Container image to use', default='us-docker.pkg.dev/jarvice/images/ubuntu-desktop:bionic')
  parser.add_argument('--label', '-l', required=False, help='Queue name')
  parser.add_argument('script', nargs=1, help='The script file to run')

  args = parser.parse_args()

  # TODO Grab Jarvice specific stuff
  # dctOpts = json.loads(args.opts)

  sUser = os.environ.get('NF_JARVICE_USER')
  sAPIKey = os.environ.get('NF_JARVICE_APIKEY')
  if (sUser is None) or (sAPIKey is None):
    print('Environment variables NF_JARVICE_USER and NF_JARVICE_APIKEY not set')
    sys.exit(-1)

  dctSubmission['user'] = {'username': sUser, 'apikey': sAPIKey}

  # Machine and label
  # Label is a per pipeline unique hex string, so that all jobs of a pipeline can be easily detected
  dctSubmission['machine'] = {'type': args.machine, 'nodes':  args.nodes}
  dctSubmission['job_label'] = args.label

  with open(args.script[0]) as f:
    data = f.read()
    dctSubmission['container'] = {'jobscript': data, 'image': args.container}

  sDockerAuth = os.environ.get('NF_JARVICE_DOCKER_AUTHS')
  if sDockerAuth:
    dctSubmission['container']['pullsecret'] = base64.b64encode(sDockerAuth.encode()).decode()

  # print(f'Running script {args.script} on machine {args.machine} with {args.nodes} nodes', file=sys.stderr)
  # print(f'Using container: {args.container}', file=sys.stderr)
  #print(dctSubmission, file=sys.stderr)
  # print(json.dumps(dctSubmission, indent=4), file=sys.stderr)

  url = 'https://jarvice-development-api.jarvicedev.com/api/jarvice/batch'
  headers = {'Content-Type': 'application/json'}
  response = requests.post(url, headers=headers, json=dctSubmission)


  # print(response.text, file=sys.stderr)

  dctRet = response.json()


  if 'error' in dctRet:
    print(dctRet)
    sys.exit(-1)

  print(dctRet['number'], end='')
